name: 'Auto rebase'
description: 'Automatically rebases pull requests that are out-of-date.'

inputs:
  github_token:
    description: The GITHUB_TOKEN secret
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'arrow-up-right'
  color: 'green'