name: 'My first github action'
description: 'This is my first github action'

inputs:
  github_token:
    description: The GITHUB_TOKEN secret
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'