name: 'Auto rebase'
description: 'Automatically rebases pull requests that are out-of-date.'

inputs:
  github_token:
    description: The GITHUB_TOKEN secret
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'