name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dylanvann/publish-github-action@v1.1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}